### ISSUE TITLE
Crashes when making changes to main.html while Cysboard is running, if "exec" is used

### ISSUE THREAD

**Issue by hotice** [mike168m/Cysboard#11]
If "exec" is used in the ~/.config/cysboard/main.html file, saving the file while Cysboard is running makes it crash. Saving the file while Cysboard is running, when exec is not used, doesn't make Cysboard crash. Here's the error:
```
$ ./Cysboard 
Cysboard: /home/andrei/Downloads/Cysboard/includes/sciter/sciter-x-dom.hpp:682: void sciter::dom::element::set_text(const WCHAR*, size_t): Assertion `r == SCDOM_OK' failed.
Aborted
```
Tested in Ubuntu 16.10 64bit.

**Comment by mike168m** [comment]
Fixed in  64049405959844951b10897d566174f85dfa999c . 
Apparently the poll timeout for the theme directory was too short.
