### ISSUE TITLE
/home/mike/.config/cysboard/get_ip.sh: not found`

### ISSUE THREAD

**Issue by psicofrenia** [mike168m/Cysboard#24]
I compiled Cysboard and, when I try to execute it, I get:

`/home/mike/.config/cysboard/get_ip.sh: not found`

In the documentation, you say that:

> If a 'main.html' file does not exist in the config directory cysboard will start with a default theme.

That is not happening

**Comment by mike168m** [comment]
Hmm, thanks for drawing my attention will look at it ASAP.

**Comment by mike168m** [comment]
Fixed in pr #25
