### ISSUE TITLE
Fails to start when using custom theme

### ISSUE THREAD

**Issue by hotice** [mike168m/Cysboard#9]
When using a custom theme, Cysboard fails to start, displaying the following error:
```
$ ./Cysboard 
Cysboard: /home/andrei/Downloads/Cysboard/includes/sciter/aux-asset.h:79: virtual aux::asset::~asset(): Assertion `_ref_cntr == 0' failed.
Aborted
```
This occurs with your theme example, as well as any simple tag, for instance trying to only display the uptime, etc. 

This occurs in Ubuntu 16.10 64bit.

**Comment by hotice** [comment]
Never mind, that was occuring because there was no ``<head>``..., I found that by taking a look at the default theme: https://github.com/mike168m/Cysboard/blob/master/sources/resources/default.htm 

Maybe you should post an example that works in its description, so you don't get bug reports like this? Anyway, I'm closing this.

**Comment by mike168m** [comment]
Thanks I'll fix the REAME.md on my next commit
